### ISSUE TITLE
AssertionError and KeyError during execution of migrate.sh

### ISSUE THREAD

**Issue by ubershy** [russell/fairy-slipper#55]
Hello.
When I try to run migrate.sh it fails with AssertionError and KeyError.
Here's the log:
http://paste.openstack.org/show/DVVdnMsayg16FFZ8tOQ8/

**Comment by kbhawkey** [comment]
Yes, I believe I just merged a fix for this.

**Comment by ubershy** [comment]
Hm, I pulled the code, deleted .venv directory, started migrate.sh again, but still see the errors. Though KeyError now sligtly changed.
http://paste.openstack.org/show/ganIQfNAXPgloICR1JpX/

**Comment by kbhawkey** [comment]
Looks like you either have newer xml files or outdated ones.  I have a pending review for a few other wadl/docbk errors, but not these.  I will grab the latest files, as my working directory is clean.

**Comment by kbhawkey** [comment]
Yes, the one complaint about "int" is what I believe to be an error in volume-api.  I have logged a bug for this and will submit a patch soon.  In the meantime, you could edit volumes-v2.wadl and change instances of "int" to "xsd:int".

**Comment by kbhawkey** [comment]
Looks like the other error is with the clustering service.  There is an error in the file.

**Comment by annegentle** [comment]
Thanks @kbhawkey! How did you get the names of the services that were throwing the errors? I used `-vvv` on the `migrate.sh` script and still just get this: http://paste.openstack.org/show/482120/

**Comment by kbhawkey** [comment]
I put in a print statement to report the files processed.

**Comment by kbhawkey** [comment]
I believe the clustering service is missing the version number, see line 9 of api-ref-clustering-v1.xml.
I can log a bug unless it is already logged.  Yes, that's it.  I just tested it.

**Comment by annegentle** [comment]
Okay, thanks @kbhawkey I'll fix that!

**Comment by kbhawkey** [comment]
Great @annegentle.  I will close this issue. Re-open as needed.
